spring.application.name=sentinelcore
spring.datasource.url=jdbc:postgresql://localhost:5432/sentinelcore
spring.datasource.username=sentineluser
spring.datasource.password=sentinelpass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true